/**
 * Baked derivations. Generated by `npm run bake` — do not hand-edit.
 *
 * A .ts module rather than a .json file so it is a plain import in both the
 * Next bundle and plain Node, with no import-attribute differences between them.
 */
import type { CachedDerivation } from "@/lib/agent/cache";

export const BAKED_DERIVATIONS: CachedDerivation[] = [
  {
    "key": "legora::legal engineer",
    "companySlug": "legora",
    "roleTitle": "Legal Engineer",
    "corpusHash": "bc550b5779ffff21",
    "role": {
      "title": "Legal Engineer",
      "summary": "This is not a generic \"legal engineer\" opening: Legora is hiring an ex-transactional lawyer to absorb work that four people (Johan, Marta, Daniel, Camille) are currently doing at 22:00 on top of client calls. Concretely, the person starting is expected to take a bounded, dated client deliverable — LE-2231, the Nordkap disclosure-letter schedule export, due 8 Sept for an 11 Sept signing — while doing the two things only a lawyer can do here: writing extraction/classification instructions around legal concepts rather than labels (the CoC rewrite that moved recall 0.71→0.94), and reviewing the eval labels that every accuracy number Legora has ever quoted a customer traces back to. The recurring failure mode they are being hired against is jurisdictional: Milan's 'cessione del contratto' miss, the French/Spanish equivalents, and Ji-won's bilingual Korean column finding are all cases where the pipeline assumed English-law drafting conventions and nobody owned the variants.",
      "evidence": [
        {
          "artifactId": "slack-legal-eng-056",
          "quote": "the person starting sept 1 is ex-M&A, 6 years, london, did basically nothing but SPAs and disclosure exercises. no coding at all, and i told them in the interview that was fine, which i believe. i want them on nordkap because they will know what a CoC consent actually looks like by day two. what i genuinely dont have is anything to hand them on day one",
          "why": "Defines the hiring bar (deep transactional drafting experience, no coding required) and admits there is no onboarding material for it."
        },
        {
          "artifactId": "ticket-le-2231-055",
          "quote": "holding this for the joiner starting 1 Sept. It is a real client deliverable with a real date, it is bounded, and the hard part is knowing what a disclosure letter schedule is supposed to look like",
          "why": "The first concrete owned deliverable is already ticketed and unassigned, waiting for this hire."
        },
        {
          "artifactId": "meeting-pairing-039",
          "quote": "(3) is not a model problem. the instruction described the label instead of the concept. rewrote it around the concept. that alone: 0.71 -> 0.88.",
          "why": "Shows the core technical contribution of the role: fixing model quality by supplying drafting knowledge, not ML work."
        },
        {
          "artifactId": "doc-eval-runbook-036",
          "quote": "I can generate 200 candidate labels in four minutes and they are worth exactly nothing until someone qualified reviews them. Right now that is Johan, Marta, Daniel and Camille, in the evenings. Every accuracy figure we have ever quoted to a customer traces back to that.",
          "why": "Names the specific capacity bottleneck this hire relieves — qualified label review in the eval harness."
        },
        {
          "artifactId": "doc-italian-writeup-054",
          "quote": "What I would tell a new person: do not start from our output. Start from the documents, decide what the right answer is yourself, and only then look at what we returned. If you start from our output you will only ever find the errors we already know about.",
          "why": "The team's own stated working method for escalations, written for the next joiner to inherit."
        },
        {
          "artifactId": "meeting-retro-030",
          "quote": "anders: when a client escalates something like this, Engagement should own the conversation end to end and legal eng should hand us a fix and a date. otherwise i have two people talking to the same partner with different levels of confidence.\n  elin: the person who read the 12 documents is the only person who can honestly say what is wrong and when it will be right.",
          "why": "The unresolved boundary dispute over whether this role talks to the escalating client or hands off a date to Engagement."
        },
        {
          "artifactId": "slack-legal-eng-018",
          "quote": "playbook repo yes, ive been fine with that since march. the extraction service no. thats the line.",
          "why": "Sets the technical permissions envelope: this person merges playbooks, not chunking or extraction changes."
        },
        {
          "artifactId": "ticket-esc-901-050",
          "quote": "What I cannot do is answer questions like 'why did the model treat this as a condition precedent rather than a covenant' or 'can we make it follow our house style on defined terms'. There are 14 of these in the doc and they have been open nine days.",
          "why": "Shows the demand from Deployment/regions for legal-engineering hours that currently has no supply — Anders notes it's the third region asking."
        },
        {
          "artifactId": "slack-legal-eng-058",
          "quote": "hard no for week one. week one they read our outputs against documents they already understand and tell us every single place we are wrong. thats worth more to us than a call and its worth more to them. week two, calls",
          "why": "Elin's explicit ramp plan for this hire, and the point where she overrules Anders on week-one client exposure."
        }
      ],
      "responsibilities": [
        "LE-2231: build the Nordkap disclosure-letter schedule export (their clause numbering, column order, docx) on top of ma.spa.change-of-control.nordkap, to the 8 Sept date, with the deal signing 11 Sept",
        "Write the legal instructions for extraction and classification steps on clause types you have actually negotiated — e.g. the consent-required / notice-only / silent split, including rules like reading German assignment and CoC provisions together before deciding",
        "Review candidate labels in Priya's eval harness and run `just eval` before/after, pasting both recall and precision into the PR per prompt review checklist v3",
        "Take items off the prompt review queue (23 in late July, down to 9 by 28 Aug) and eventually earn approval rights, currently held only by Elin, Johan and Daniel",
        "Own named-account escalations the way ESC-882 was owned: read every document before touching the playbook, ship a retrieval/variants fix plus a jurisdiction note plus new eval documents — explicitly not a keyword list",
        "Write drafting notes that travel across jurisdictions (Italian, French, Spanish, Portuguese equivalents of assignment/change-of-control) instead of patching one playbook at a time",
        "Write the fork description before building — one paragraph in the client's own words, what changed versus parent, jurisdictions tested, who to ask when it breaks (Nina's naming draft, Nordkap being the 6th CoC fork)",
        "Sit on customer calls that Deployment and Engagement cannot answer — the Sakabe & Partners Wednesday Tokyo call, Whitfield Grange precedent-bank questions — and log the questions",
        "Contribute the written artefacts that do not exist yet: the Legal Engineering equivalent of Tobias's day-1 setup doc, and the monthly one-paragraph writeups Elin is chasing"
      ],
      "firstWeekOutcomes": [
        "A written list of every place Legora's output is wrong on SPA and disclosure documents you already understand — produced before you are put on any client call, per Elin's ramp",
        "LE-2231 scoped with Nordkap's actual ask captured in one paragraph in the fork description before any build, and the docx template layer started (Johan's estimate: half a day, he'll take the docx if it fights back)",
        "A batch of eval labels reviewed in ma.spa.change-of-control so Priya's harness is not blocked on evening volunteers",
        "At least one item cleared from the prompt review queue against checklist v3, with jurisdiction named in the instruction description",
        "One paragraph in the team Notion about something you figured out, hitting Elin's Friday deadline — the first onboarding artefact that did not previously exist",
        "Playbook repo write access requested through #eng-platform and used for one real merge; no attempt on extraction service write"
      ],
      "keyPeople": [
        {
          "name": "Elin Sandberg",
          "why": "Hiring manager, holds LE-2231 for this joiner, sets the week-one 'read the outputs, not the calls' plan, and is one of only three people who can approve a prompt."
        },
        {
          "name": "Johan Lindqvist",
          "why": "Owns the Nordkap CoC work and the SPA/clause-extraction pipeline; will be the buddy for the disclosure schedule and the model of how the job is actually done."
        },
        {
          "name": "Priya Raghunathan",
          "why": "Runs the eval harness and will pair on turning drafting knowledge into recall/precision movement — she explicitly cannot judge a materiality qualifier herself."
        },
        {
          "name": "Anders Wikström",
          "why": "Brings the client asks and the dates (Nordkap disclosure letter, Ardent) and wants someone senior on the call — the person this hire will have to negotiate escalation comms with."
        },
        {
          "name": "Nina Ekström",
          "why": "Needs a Legal Engineering owner for the WF-411 config wording so the ~340 forks stop multiplying; that unstaffed job may land here."
        }
      ],
      "openQuestions": [
        "Escalation ownership is genuinely undecided: Anders wants Engagement to own the client conversation and receive a fix plus a date; Elin says the person who read the documents must be on the call. Both were asked to write half a page and, as of 28 Aug, neither had.",
        "Week-one client exposure: Anders says put them on client calls immediately, Elin said 'hard no for week one'. Elin's view won in the thread but LE-2231's client call is still 'we can argue about that separately'.",
        "Who owns the playbook library. Nina got three answers in one week; Elin says her team maintains M&A and diligence only, Anders says Engagement owns 340 forks 'which is obviously wrong, but it is the true answer'. Carried to the offsite twice with no decision.",
        "The jurisdiction variants layer Camille has asked for three times has no owner — Nina was asked to scope it. Whether this hire builds and owns it, or just files notes into individual playbooks, is unsettled.",
        "Expected coding level is contested. Elin: whoever writes the spec must have negotiated the clause, tooling is secondary. Daniel merges schema changes himself. Camille says 'half of us cannot read python' and the debate is partly a skills one. Nobody has written down what the floor is.",
        "Permissions: playbook repo write is routinely approved, extraction service write is Tobias's line — but LE-2214, LE-2205 and the Italian fix all live in the extraction service, so it is unclear how this person ships retrieval/chunking fixes they diagnose.",
        "Approval rights: the prompt review checklist says 'Not covered here: who is allowed to approve' and flags the Elin/Johan/Daniel bottleneck. Whether this hire is expected to become an approver, and on what timeline, is not stated.",
        "APAC coverage: three regions are asking for a Legal Engineer on recurring calls and only four people can do it. Whether that becomes part of this Europe-based role or a separate hire is unaddressed.",
        "Location and reporting line: the 1 Sept joiner is London ex-M&A, but the Nordkap work, the review queue and the floor 6 desks are Stockholm — and Legal Engineering already has 18 desks for 24 people."
      ]
    },
    "plan": {
      "role": "Legal Engineer",
      "days": [
        {
          "day": 1,
          "theme": "Find and write down every place our output is wrong on documents you already know",
          "tasks": [
            {
              "id": "d1-t1",
              "title": "Write an error log for the Nordkap change-of-control output",
              "why": "Elin's stated ramp for you is explicit: week one you read our outputs against documents you already understand and tell us every place we are wrong — before any client call. Nordkap's deal signs 11 Sept and the CoC output is what Nordkap will drop into a disclosure letter.",
              "context": "The workflow is ma.spa.change-of-control with a client fork ma.spa.change-of-control.nordkap; the Nordkap set is 40 SPAs from their VDR, but only the ~15 Johan used in his pairing session with Priya are in the tenant — the other 25 have not landed and Anders is chasing Nordkap, so do not wait for them. After that pairing session the set sits at 0.94 recall / 0.91 precision, and the misses Johan found fell into exactly three kinds: (1) clause split across two sub-clauses, (2) CoC defined by reference to a defined term in Schedule 1, (3) the words 'change of control' never appear at all — it is drafted as a transfer of more than 50% of the shares. Separately, LE-2214 records that in 6 of the 40 the governing law provision sits in Schedule 4 (Interpretation) or is cross-referenced out to a framework agreement and we return null; v1 of that fix is scoped to schedules only and gets 4 of the 6, so expect to still see nulls. Work Marta's way, written up in her Ardent (ESC-882) note: read each SPA and decide what the right answer is yourself first, then look at what we returned — if you start from our output you will only find errors we already know about. Two things are already decided and should not be reopened: extraction and classification are separate model calls (one schema cost ~8pp of extraction recall on the June indemnity work), and a precision drop in exchange for recall is the correct trade for diligence work (prompt review checklist v3, item 6). You do not need the local dev stack or Python for this; you need the tenant and the PDFs. Ask Tobias in #eng-platform for tenant access plus playbook repo write (he approved 7 of those last week) — do not ask for extraction service write, that is his stated line.",
              "doneWhen": "A doc posted in #legal-eng listing, per document, every wrong or missing CoC output you found, each tagged with Johan's miss type 1/2/3 or a new type you name and describe.",
              "askIfStuck": "Johan Lindqvist",
              "estimateMins": 150
            },
            {
              "id": "d1-t2",
              "title": "Write the LE-2231 fork description before anything is built",
              "why": "LE-2231 (Nordkap disclosure-letter schedule export, due 8 Sept, deal signs 11 Sept) is unassigned and being held for you, and Nina has asked specifically that whoever builds a fork writes down what the client actually asked for before building — this will be the 6th client fork of the CoC playbook and none of the six know about each other.",
              "context": "Anders posted the ask in #customer-escalations on 24 Aug: Nordkap want the CoC output as a schedule they can drop straight into the disclosure letter, formatted their way, with their clause numbering. Johan's read is that this is a template layer on top of the existing fork output, not new extraction, about half a day of build, and he will take the docx part if it fights back. Nina's draft doc 'Playbook naming + fork conventions' sets the naming shape <practice>.<instrument>.<task>[.<client>] and requires every fork description to answer four things in the author's own words: (1) what the client actually asked for, one paragraph in their language not ours, (2) what changed versus the parent playbook, (3) which jurisdictions it was tested against — this is the Milan lesson, (4) who to ask when it breaks. Nina is also sampling forks for WF-411 because ~55% of the ~340 client forks are one of three things (output format change, jurisdiction patch, one extra field), so say plainly which of the three this is. You have negotiated and run disclosure exercises; you know what a disclosure schedule is supposed to look like, which is the reason this ticket was held for you — where the exact column order or numbering convention is not recorded anywhere, write it as a numbered open question for Anders rather than guessing. Do not join or request the Nordkap client call this week: Elin overruled Anders on week-one client exposure and that argument is still live.",
              "doneWhen": "LE-2231 has a comment from you containing the four-part fork description plus a numbered list of open questions addressed to Anders.",
              "askIfStuck": "Anders Wikström",
              "estimateMins": 75
            },
            {
              "id": "d1-t3",
              "title": "Review a batch of candidate eval labels in ma.spa.change-of-control",
              "why": "Priya can generate 200 candidate labels in four minutes and they are worth nothing until someone qualified reviews them; today that is Johan, Marta, Daniel and Camille in the evenings, and every accuracy figure Legora has ever quoted a customer traces back to that queue. On 19 Aug she needed ~200 labelled by Thursday and there was nobody.",
              "context": "Priya's runbook 'Eval harness — how to run it (and why the numbers move)' is in Notion / Applied ML; ping her for an account. You run `just eval --set=ma.spa.change-of-control --rev=HEAD` and get recall, precision, a per-document breakdown and a diff against the last run. Her explicit position: you do not need to be able to write Python, you need to be able to read a contract, and 'want me to explain what a threshold is — also ping me, it is a ten minute conversation and it is not a stupid question.' The single most useful thing you produce here is the distinction she cannot make herself: roughly half of apparent misses are wrong labels, not model failures, and only someone who has drafted the clause can tell which. The ma.spa.* sets hold about 120 documents; treat anything under ~50 as a vibe. Aim for 60 labels, correct/incorrect, one line of reasoning on every disagreement, in the concept language you'd use with a client rather than 'clause type'. Note that the overnight eval run was killed once by PLAT-1190 and results came back two hours late — if a run looks stale, check with Priya before assuming a regression.",
              "doneWhen": "60 candidate labels in ma.spa.change-of-control marked correct/incorrect with a reason on each disagreement, and a note in #eng-platform stating how many of your disagreements were label errors versus model errors.",
              "askIfStuck": "Priya Raghunathan",
              "estimateMins": 100
            }
          ]
        },
        {
          "day": 2,
          "theme": "Ship the dated deliverable and hand work to three other people",
          "tasks": [
            {
              "id": "d2-t1",
              "title": "Build a first draft of the Nordkap disclosure-schedule docx export",
              "why": "LE-2231 is due 8 Sept for an 11 Sept signing, it is the deliverable Elin held open for you, and the alternative for Nordkap is a trainee doing it by hand for 40 hours. Nordkap is the largest Nordic account.",
              "context": "Build on top of the ma.spa.change-of-control.nordkap output, using the fork description you wrote yesterday as the spec — if an open question there is still unanswered, build to your own best legal judgement of what a disclosure letter schedule should look like and flag the assumption rather than stalling. This is a template/output layer only: it lives in the playbooks repo, where Tobias has been fine with legal engineers merging since March, and it needs no change to the extraction service (that is his hard line, and Priya already owns the retrieval work in LE-2214 and LE-2205). Johan estimated half a day and offered to take the docx generation if it fights back — take him up on that rather than burning an afternoon on formatting. Generate the schedule from the ~15 Nordkap documents currently in the tenant, including the ones where governing law comes back null, so Anders can see how the nulls read to a client (they read as 'no governing law clause', which is wrong and alarming). Name the fork per Nina's convention and keep the four-part description attached to it.",
              "doneWhen": "A generated draft docx schedule attached to LE-2231, plus a list in the ticket of the formatting or numbering items you had to assume.",
              "askIfStuck": "Johan Lindqvist",
              "estimateMins": 120
            },
            {
              "id": "d2-t2",
              "title": "Draft the consent-required / notice-only / silent decision rules",
              "why": "Nordkap do not just want the CoC clauses extracted, they want each one flagged consent-required, notice-only or silent — and Marta's read is that it is a judgement call on roughly 1 in 6, with German drafting burying the answer in the assignment clause. Elin's rule is that whoever writes the spec must have actually negotiated the clause.",
              "context": "Johan wrote a first version of these classification instructions during the 20 Aug pairing session, including the rule that German assignment and CoC provisions must be read together before deciding; your job is to turn that into a written decision rule good enough for someone who joins in October. The single most important lesson from that session: recall moved 0.71 to 0.88 purely because the instruction had described the label instead of the concept — write around the legal concept (e.g. a transfer of more than 50% of the shares is a change of control even where those words never appear), not around the words. Also from that session: cutting few-shot examples from 5 to 3 gained another 6pp because the model was pattern-matching on a weird earnout-linked example, so be sparing and pick clean ones. Per prompt review checklist v3 item 2, every example must be a real clause from a document we are allowed to use — no paraphrases, no invented clauses; if you cannot find a real one for a category, that is itself a finding and you write it down. The classify step stays a separate model call from extraction; that is settled. Marta owns the assignment and change-of-control playbooks and the jurisdiction edge cases, so hand it to her when it reads right. Put it in Notion / Legal Engineering and link it in #legal-eng — Elin is chasing everyone for one written paragraph about something they figured out this month, and this counts.",
              "doneWhen": "A doc in Notion / Legal Engineering setting out the consent/notice/silent decision rules with real example clauses and an explicit list of cases you would refuse to classify, linked in #legal-eng.",
              "askIfStuck": "Marta Nowak",
              "estimateMins": 90
            },
            {
              "id": "d2-t3",
              "title": "Take one item off the prompt review queue against checklist v3",
              "why": "The queue hit 23 in late July with the oldest item from 29 July; it is down to 9 because Daniel and Camille took four each. Elin's framing: an unreviewed prompt that ships is not an internal problem, it is a client in a room being told the wrong thing about their own contract. Approval sits only with Elin, Johan and Daniel and that is a known bottleneck.",
              "context": "The queue and 'Prompt review checklist v3' both live in Notion / Legal Engineering; a review is about 20 minutes of checklist plus however long the documents take. Take the oldest item, not the easiest. Work all seven points, and note the two v3 additions: item 1 requires the instruction to name the jurisdictions it was written against and say so in the description if it silently assumes English-law drafting (added after the Milan miss), and item 6 says a precision drop with a recall rise is usually right for diligence and usually wrong for drafting — decide which one the prompt is in and say so. Item 5 requires you to run the eval set before and after and paste both recall and precision, not whichever moved the way you wanted; use the harness account you got from Priya. Item 4 wants initials and date from someone who has actually drafted or negotiated the clause type — that is you, and it is the part nobody else in the queue can supply. You are not an approver yet, so end by either handing it to Elin, Johan or Daniel with a recommendation, or sending it back with named changes.",
              "doneWhen": "One prompt review queue item carries your written review against all seven checklist points, with before/after recall and precision pasted in, and has been either passed to an approver with a recommendation or returned with named changes.",
              "askIfStuck": "Elin Sandberg",
              "estimateMins": 75
            },
            {
              "id": "d2-t4",
              "title": "Answer the pure-law questions in ESC-901 in writing for Rahul",
              "why": "Rahul has 14 customer questions from the Sakabe & Partners Tokyo pilot open for nine days and has been giving answers that are about the software rather than about the contracts — his words: 'I am starting to make things up in a professional tone.' Anders flagged this is the third region asking for legal-engineering hours against four people who can supply them.",
              "context": "ESC-901 on the ESC board holds all 14 questions; it is unassigned. Several are not product questions at all — 'why did the model treat this as a condition precedent rather than a covenant' and 'can we make it follow our house style on defined terms' are transactional-drafting questions you can answer today. Answer those in prose Rahul can paste to the client without translation, and tag the rest either for Ji-won (he has taken the Wednesday call, which starts two hours before his day) or as a genuine product gap for Nina. Do not join the call: Elin's ruling stands that week one is reading outputs, not client exposure, and week two is calls. Elin has already said the logged question list is worth more than the call itself, so the value here is the written record, not the meeting. Where an answer depends on how our pipeline actually behaves rather than on law, say so plainly and name who owns it — Priya for retrieval and chunking, Nina for anything that needs a config surface (see WF-411).",
              "doneWhen": "ESC-901 has a comment from you answering at least six of the 14 questions in client-ready language, with each remaining question reassigned by name to Ji-won, Priya or Nina.",
              "askIfStuck": "Rahul Menon",
              "estimateMins": 60
            }
          ]
        }
      ]
    },
    "grounding": {
      "kept": 9,
      "dropped": 0
    },
    "derivedAt": "2026-08-29T08:05:57.350Z"
  }
];
