/**
 * Re-bake the demo hire into `lib/seed/hires.ts`.
 *
 *   npm run bake:hire
 *
 * Picks the hire with the most blockers and messages out of `data/hires.json` —
 * that is the one with something to show — pins it to a stable id, and writes it
 * as a committed module. See the comment in `lib/agent/hires.ts` for why: on
 * serverless there is otherwise no hire at all, so `/manager` and `/hire/[id]`
 * are both blank on the deployed URL.
 */
import { promises as fs } from "node:fs";

const DEMO_ID = "demo-legal-engineer";

const raw = JSON.parse(await fs.readFile("data/hires.json", "utf8"));
let hires = raw.hires ?? raw;
if (!Array.isArray(hires)) hires = Object.values(hires);
if (!hires.length) { console.error("No hires in data/hires.json."); process.exit(1); }

const demo = hires.reduce((best, h) =>
  (h.blockers?.length ?? 0) * 100 + (h.messages?.length ?? 0) >
  (best.blockers?.length ?? 0) * 100 + (best.messages?.length ?? 0) ? h : best);
demo.id = DEMO_ID;

const banner = `/**
 * The demo hire, committed so it ships inside the bundle.
 * Generated by \`npm run bake:hire\` — do not hand-edit.
 *
 * Why: see lib/agent/hires.ts. On serverless the disk store does not exist, so
 * without this the deployed /manager is empty and there is no hire page to open.
 */
import type { HireState } from "@/lib/types";

export const BAKED_HIRES: HireState[] = `;

await fs.writeFile("lib/seed/hires.ts", banner + JSON.stringify([demo], null, 2) + ";\n", "utf8");
console.log(`Baked ${demo.name} · ${demo.roleTitle} · ${demo.messages?.length ?? 0} messages · ${demo.blockers?.length ?? 0} blockers`);
console.log(`  stable url: /hire/${DEMO_ID}`);
