/**
 * Re-bake the demo hire into `lib/seed/hires.ts`.
 *
 *   npm run bake:hire
 *
 * Picks the hire with the most blockers and messages out of `data/hires.json` —
 * that is the one with something to show — pins it to a stable id, and writes it
 * as a committed module. See the comment in `lib/agent/hires.ts` for why: on
 * serverless there is otherwise no hire at all, so `/manager` and `/hire/[id]`
 * are both blank on the deployed URL.
 *
 * IT BAKES THE COHORT, NOT JUST THE ONE HIRE
 *
 * `/manager` only renders "Where two ramps touch" when a company has two people
 * ramping at once, because that is the only situation in which one planner has
 * to divide scope with another. Baking a single hire therefore ships the
 * coordination feature in a state where it can never fire — the code is live,
 * the section is unreachable, and the deployed product looks like it does not
 * have the thing that most distinguishes it.
 *
 * So every other still-ramping hire at the same company is baked alongside the
 * primary one. Their ids are pinned from the role title rather than left as
 * UUIDs, so the URLs survive a re-bake and can go in a doc.
 */
import { promises as fs } from "node:fs";

const DEMO_ID = "demo-legal-engineer";

const raw = JSON.parse(await fs.readFile("data/hires.json", "utf8"));
let hires = raw.hires ?? raw;
if (!Array.isArray(hires)) hires = Object.values(hires);
if (!hires.length) { console.error("No hires in data/hires.json."); process.exit(1); }

const demo = hires.reduce((best, h) =>
  (h.blockers?.length ?? 0) * 100 + (h.messages?.length ?? 0) >
  (best.blockers?.length ?? 0) * 100 + (best.messages?.length ?? 0) ? h : best);
demo.id = DEMO_ID;

// `stillRamping` rather than a re-implementation: the definition of "currently
// ramping" belongs to the cohort module, and a second copy here would drift.
const { stillRamping } = await import("@/lib/agent/cohort");

const slugId = (roleTitle) =>
  "demo-" + String(roleTitle).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

// The store can hold two records for one person: the pinned bake that was
// written back to disk on a previous run, and the live record from the real
// derivation. They are the same hire, so identity here is the person and the
// role rather than the id — the same key `dropShadowedBakes` uses — otherwise
// the roster ships with two Rebecca Hartleys and two `demo-legal-engineer`s.
const identity = (h) =>
  `${h.companySlug}\u0000${h.name.trim().toLowerCase()}\u0000${h.roleTitle.trim().toLowerCase()}`;

const seen = new Set([identity(demo)]);
const cohort = [];
for (const h of hires) {
  if (h === demo) continue;
  if (h.companySlug !== demo.companySlug) continue;
  if (!stillRamping(h)) continue;
  const key = identity(h);
  if (seen.has(key)) continue;
  seen.add(key);
  h.id = slugId(h.roleTitle);
  cohort.push(h);
}

const baked = [demo, ...cohort];

// Pinning the hire's id left every nested record still pointing at the UUID it
// had when it was derived, so a baked blocker's hireId did not match the hire
// carrying it. Nothing reads that field today, which is exactly why it would
// have gone unnoticed until something did.
for (const h of baked) {
  for (const row of [...(h.blockers ?? []), ...(h.messages ?? []), ...(h.driftNotes ?? [])]) {
    if (row && typeof row === "object" && "hireId" in row) row.hireId = h.id;
  }
}

const banner = `/**
 * The demo hire, committed so it ships inside the bundle.
 * Generated by \`npm run bake:hire\` — do not hand-edit.
 *
 * Why: see lib/agent/hires.ts. On serverless the disk store does not exist, so
 * without this the deployed /manager is empty and there is no hire page to open.
 */
import type { HireState } from "@/lib/types";

export const BAKED_HIRES: HireState[] = `;

await fs.writeFile("lib/seed/hires.ts", banner + JSON.stringify(baked, null, 2) + ";\n", "utf8");
for (const h of baked) {
  console.log(`Baked ${h.name} · ${h.roleTitle} · ${h.messages?.length ?? 0} messages · ${h.blockers?.length ?? 0} blockers`);
  console.log(`  /hire/${h.id}`);
}
